confluence: null
maintainer: mdyjasLifeWorks
project_description: Onboarding task
project_name: onboarding_marcin_dyjas
python_version: '3.9'
repository: https://github.com/workivate/onboarding-marcin-dyjas.git
sentry_dsn_integration: null
sentry_dsn_integration_au: null
sentry_dsn_live: null
sentry_dsn_singletenant_test: null
sentry_dsn_tdbank: null
sentry_dsn_test: null
sentry_dsn_test_au: null
