openapi: 3.0.3

servers:
  - url: https://services.io.integration.lifeworks.com/onboarding-marcin-dyjas
    description: Integration
  - url: https://services.io.test.lifeworks.com/onboarding-marcin-dyjas
    description: Test
  - url: https://services.io.lifeworks.com/onboarding-marcin-dyjas
    description: Live

info:
  description: Onboarding task
  version: "1.0.0"
  title: onboarding-marcin-dyjas

paths:
  /ping:
    $ref: "paths/ping.yaml#/pathInfo"
  /status:
    $ref: "paths/status.yaml#/pathInfo"
  /onboarding/{name}:
    $ref: "paths/onboarding.yaml#/pathInfo"
